version: "2.4"

services:

  arangodb:
    image: arangodb/arangodb
    ports:
      - "8529:8529"
    volumes:
      - ./arangodb_data:/var/lib/arangodb3
    environment:
      ARANGO_ROOT_PASSWORD: root_pass
