[[runners]]
  name = "a9a3dd7b82bd"
  url = "https://gitlab.actcognitive.org/"
  token = "GR13489411zEnMAxGGYzUbd37rrQo"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "alpine"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0